### ISSUE TITLE
Add some more functionality to the code.

### ISSUE THREAD

**Issue by appuCoding** [patilav/Web-Development-CS5610#1]
Your experiments are good .From Next experiments add some more functionality , It k to take code from W3 schools site and refer them but try to modify that code and add some tweaks to make it different.
Or take it from different websites and tweak them. 

Also explain the code in your own words  . You can refer it from website but try to explain it in your own instead of just copy paste.

**Comment by patilav** [comment]
Hi Sneha, 

As I was learning jQuery for the first time. I tried to do smaller experiments 
I will try to add more functionality and will try to integrate 2-3 technologies together from next time.
Thanks for the idea! :)
